import { realms } from '../data/realms.js';
import { saveGame } from './Save.js';

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export class Game {
  constructor(canvas,input,ui){this.c=canvas;this.x=canvas.getContext('2d');this.input=input;this.ui=ui;this.realmIndex=0;this.player={x:.5,y:.84,hp:100,attack:0,inv:0};this.enemy=null;this.step=0;this.memories=[];this.journal=[];this.running=false;this.last=0;this.resize();addEventListener('resize',()=>this.resize())}
  resize(){this.c.width=innerWidth*devicePixelRatio;this.c.height=innerHeight*devicePixelRatio;this.x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
  get realm(){return realms[this.realmIndex]}
  start(saved){if(saved){this.realmIndex=saved.realmIndex||0;this.memories=saved.memories||[];this.journal=saved.journal||[];this.step=saved.step||0}this.running=true;this.ui.showGame(this);this.message(`Entered ${this.realm.name}`,1500);requestAnimationFrame(t=>this.loop(t))}
  loop(t){if(!this.running)return;const dt=Math.min(.04,(t-this.last||16)/1000);this.last=t;this.update(dt);this.draw(t/1000);requestAnimationFrame(n=>this.loop(n))}
  update(dt){const i=this.input,p=this.player;if(!this.ui.dialogueOpen&&!this.ui.journalOpen){let dx=(i.down('KeyD','ArrowRight')?1:0)-(i.down('KeyA','ArrowLeft')?1:0),dy=(i.down('KeyS','ArrowDown')?1:0)-(i.down('KeyW','ArrowUp')?1:0);let speed=(i.down('ShiftLeft','ShiftRight')?1.05:.58)*dt;if(dx||dy){const l=Math.hypot(dx,dy);p.x=clamp(p.x+dx/l*speed,.08,.92);p.y=clamp(p.y+dy/l*speed,.25,.91)}if(i.hit('Space'))this.attack();if(i.hit('ShiftLeft')||i.hit('ShiftRight')){p.inv=.45;p.x=clamp(p.x+.08,.08,.92)}if(i.hit('KeyE'))this.interact();if(i.hit('KeyJ'))this.ui.toggleJournal(this);if(p.y<.30&&this.step>=2)this.transition()}p.attack=Math.max(0,p.attack-dt);p.inv=Math.max(0,p.inv-dt);this.enemy?.update(dt);i.end();this.ui.update(this)}
  attack(){const p=this.player;if(p.attack)return;p.attack=.28;if(this.enemy&&Math.hypot(p.x-this.enemy.x,p.y-this.enemy.y)<.16){this.enemy.hp-=28;this.message('The curse recoils.',600);if(this.enemy.hp<=0){this.enemy=null;this.message('The path is clear.',900)}}}
  interact(){const p=this.player;if(this.enemy){this.message('A hostile spirit bars the way.',1000);return}if(p.y>.66&&this.step===0){this.step=1;this.add('Lore — '+this.realm.name,this.realm.lore);this.dialogue('ANCIENT CHRONICLE',this.realm.lore);return}if(p.y<.48&&this.step===1){this.step=2;this.memories.push(this.realm.name);this.add('Memory — '+this.realm.name,this.realm.memory);this.dialogue('PIUU MEMORY',this.realm.memory);return}this.message(this.step<2?'Search the landmark for a memory.':'Follow the pale road north.',1000)}
  dialogue(label,text){this.ui.dialogue(label,text,()=>{if(this.step===1&&!this.enemy)this.enemy=new Enemy(this);this.persist()})}
  transition(){if(this.realmIndex===realms.length-1){this.finish();return}this.realmIndex++;this.step=0;this.player.x=.5;this.player.y=.84;this.enemy=null;this.ui.update(this);this.message(`Realm discovered: ${this.realm.name}`,1900);this.persist()}
  add(title,text){this.journal.push({title,text})}
  persist(){saveGame({realmIndex:this.realmIndex,step:this.step,memories:this.memories,journal:this.journal})}
  finish(){this.running=false;this.persist();this.ui.finish()}
  message(text,time=1400){this.ui.toast(text,time)}
  draw(time){const g=this.x,w=innerWidth,h=innerHeight,r=this.realm,[a,b,c]=r.palette;g.clearRect(0,0,w,h);const sky=g.createLinearGradient(0,0,0,h);sky.addColorStop(0,a);sky.addColorStop(.53,b);sky.addColorStop(1,'#050609');g.fillStyle=sky;g.fillRect(0,0,w,h);for(let n=0;n<34;n++){let x=(Math.sin(n*55.3)*.5+.5)*w,y=((n*73)%100)/100*h*.76;g.fillStyle=`rgba(230,230,220,${.025+(n%4)*.012})`;g.beginPath();g.arc(x,y,30+n%6*18,0,7);g.fill()}g.fillStyle='rgba(5,6,9,.5)';g.beginPath();g.moveTo(w*.5,h*.16);g.lineTo(w*.94,h);g.lineTo(w*.06,h);g.fill();g.strokeStyle='rgba(220,210,186,.18)';g.lineWidth=2;for(let y=.34;y<1;y+=.1){g.beginPath();g.moveTo(w*.5-(y-.2)*w*.35,h*y);g.lineTo(w*.5+(y-.2)*w*.35,h*y);g.stroke()}this.landmark(g,w,h);this.drawPlayer(g,w,h);if(this.enemy)this.enemy.draw(g,w,h,time);if(this.step<2){this.marker(g,w,h,this.step===0?.74:.40)}else this.marker(g,w,h,.22,'↑')}
  landmark(g,w,h){let y=this.step===0?.72:.39;g.fillStyle='rgba(10,8,12,.75)';g.fillRect(w*.42,h*y-60,w*.16,65);g.fillStyle='#b8a67b';g.font='12px Cinzel';g.textAlign='center';g.fillText(this.step===0?'✦  LANDMARK  ✦':'◈  MEMORY  ◈',w*.5,h*y-32)}
  marker(g,w,h,y,t='E'){g.fillStyle='#f0d68d';g.font='20px Cinzel';g.textAlign='center';g.fillText(t,w*.5,h*y-72)}
  drawPlayer(g,w,h){let p=this.player,x=p.x*w,y=p.y*h;g.save();g.translate(x,y);g.fillStyle=p.inv?'#fff0c0':'#ded5bd';g.beginPath();g.arc(0,-20,8,0,7);g.fill();g.fillStyle='#2d3542';g.beginPath();g.moveTo(-12,20);g.lineTo(-7,-10);g.lineTo(7,-10);g.lineTo(12,20);g.fill();if(p.attack){g.strokeStyle='#f0d68d';g.lineWidth=4;g.beginPath();g.arc(10,-5,28,-1.2,1);g.stroke()}g.restore()}
}
class Enemy {constructor(game){this.game=game;this.x=.5;this.y=.50;this.hp=100;this.t=0}update(dt){this.t+=dt;let p=this.game.player,d=Math.hypot(this.x-p.x,this.y-p.y);if(d<.28){this.x+=(p.x-this.x)/d*dt*.12;this.y+=(p.y-this.y)/d*dt*.12;if(d<.09&&p.inv<=0){p.hp-=15*dt;if(p.hp<=0){p.hp=100;p.x=.5;p.y=.84;this.game.message('The road returns you to the checkpoint.')}}}}draw(g,w,h){let x=this.x*w,y=this.y*h;g.save();g.translate(x,y);g.fillStyle='rgba(14,8,23,.9)';g.beginPath();g.arc(0,-20,18,0,7);g.fill();g.fillStyle='#b15f87';g.fillRect(-16,-48,32,5);g.fillStyle='#e1b5c5';g.font='10px Cinzel';g.textAlign='center';g.fillText(this.game.realm.enemy,0,-60);g.restore()}}
